name: peachstateintertie
region: atl

static_sites:
  - name: peachstateintertie
    environment_slug: html
    source_dir: /
    error_document: 404.html

    github:                              # ← MUST be "github", not "git"
      repo: discerningowl/PSI-web   # ← short username/repo format
      branch: main
      deploy_on_push: true                 # ← this turns auto-deploy on

    routes:
      - path: /

    headers:
      - pattern: "**"
        headers:
          X-Frame-Options: "DENY"
          X-Content-Type-Options: "nosniff"
          Referrer-Policy: "strict-origin-when-cross-origin"
          Permissions-Policy: "geolocation=(), microphone=(), camera=()"
      - pattern: "**/*.html"
        headers:
          Cache-Control: "public, max-age=3600, must-revalidate"
      - pattern: "**/images/**"
        headers:
          Cache-Control: "public, max-age=31536000, immutable"
      - pattern: "**/*.css"
        headers:
          Cache-Control: "public, max-age=31536000, immutable"
      - pattern: "**/*.js"
        headers:
          Cache-Control: "public, max-age=31536000, immutable"

domains:
  - domain: peachstateintertie.com
    type: PRIMARY
    zone: peachstateintertie.com
  - domain: www.peachstateintertie.com
    type: ALIAS
    zone: peachstateintertie.com